[v,f] = stlRead('roboHand.stl');
v(:,4) = 1;
tform = makehgtform('translate',5,8,19,'axisrotate',[2,5,1],pi/3);
v = (tform * v.').';
v = v(:,1:3);
stlPlot(v,f);
camlight('headlight');
material('dull');
figure;
v(:,4) = 1;
v = (inv(tform) * v.').';
v = v(:,1:3);
stlPlot(v,f);
camlight('headlight');
material('dull');